name: Chatbook Ubuntu 22.04

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Unzip out.zip to current directory
      run: unzip out.zip -d .

    - name: Set up GitHub Token
      run: echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV

    - name: Install dependencies
      run: npm install

    - name: Chatbook Ubuntu
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: npm run build

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Chatbook 0.1.0.deb
        path: dist/*.deb
